import { prisma } from "@reachdem/database";
import { createWorkspaceApiKey } from "@reachdem/auth/api-key";

async function generateTestApiKey() {
  const organizationId =
    process.env.TEST_ORG_ID || "f19dfc64-9b68-4ce9-8701-bae71cccbaab";
  const userId = process.env.TEST_USER_ID || "SjBxeFpOKvzu2InUw9wD9GYAjE9toZNO";

  try {
    const apiKey = await createWorkspaceApiKey({
      organizationId,
      createdBy: userId,
      title: "Test API Key generated by script",
      type: "public-test",
    });

    console.log(
      `\nSuccessfully created test API Key for org ${organizationId}!\n`
    );
    console.log(`API KEY: ${apiKey.token}\n`);
    console.log(`Example curl:\n`);
    console.log(`curl -X GET "http://localhost:3000/api/v1/campaigns" \\`);
    console.log(`     -H "Authorization: Bearer ${apiKey.token}" \\`);
    console.log(`     -H "Accept: application/json"\n`);
  } catch (error) {
    console.error(
      "Failed to create API key. Ensure the TEST_ORG_ID and TEST_USER_ID exist in the DB."
    );
    console.error(error);
  }
}

generateTestApiKey()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
  });
