import { createHash, randomBytes } from "crypto";
import { prisma } from "@reachdem/database";

async function generateTestApiKey() {
  const organizationId =
    process.env.TEST_ORG_ID || "f19dfc64-9b68-4ce9-8701-bae71cccbaab";
  const userId = process.env.TEST_USER_ID || "SjBxeFpOKvzu2InUw9wD9GYAjE9toZNO";

  const idBase = randomBytes(4).toString("hex");
  const secret = randomBytes(24).toString("base64url");
  const salt = randomBytes(16).toString("base64url");

  const fullApiKey = `rdm_${idBase}_${secret}`;

  const hashedToken = createHash("sha256")
    .update(`${salt}:${secret}`)
    .digest("hex");

  try {
    await prisma.apiKey.create({
      data: {
        id: idBase,
        organizationId,
        token: hashedToken,
        salt,
        redacted: secret.slice(-4),
        title: "Test API Key generated by Copilot",
        type: "public-test",
        createdBy: userId,
      },
    });

    console.log(
      `\nSuccessfully created test API Key for org ${organizationId}!\n`
    );
    console.log(`API KEY: ${fullApiKey}\n`);
    console.log(`Example curl:\n`);
    console.log(`curl -X GET "http://localhost:3000/api/v1/campaigns" \\`);
    console.log(`     -H "Authorization: Bearer ${fullApiKey}" \\`);
    console.log(`     -H "Accept: application/json"\n`);
  } catch (error) {
    console.error(
      "Failed to create API key. Ensure the TEST_ORG_ID and TEST_USER_ID exist in the DB."
    );
    console.error(error);
  }
}

generateTestApiKey().catch(console.error);
